#!/usr/bin/env python3

"""This is a pipeline file that combines all models
   For every individual model training, see word_align file
"""

import os
import argparse

def arg_parser(name: str = "Pipeline") -> dict:
    parser = argparse.ArgumentParser(description=name)
    parser.add_argument(
        "-n",
        metavar="sentences_number",
        dest="num_sents",
        default=100,
        type=int,
        help="Number of sentences to use for training and alignment"
    )
    args = parser.parse_args()
    args_dict = vars(args)
    return args_dict
    

if __name__ == "__main__":
    args = arg_parser()
    num = args["num_sents"]
    os.system("python3 word_align.py -m IBM1 -n {} > t_ibm.a".format(num))
    os.system("python3 word_align.py -m IBM1 -n {} --rt > t_ibm_rt.a".format(num))
    os.system("python3 word_align.py -n {} > t_hmm.a".format(num))
    os.system("python3 word_align.py -n {} --rt > t_hmm_rt.a".format(num))
    os.system("python3 word_align.py -n {} --rs > t_hmm_rs.a".format(num))
    os.system("python3 word_align.py -n {} --rt --rs > t_hmm_rt_rs.a".format(num))
    os.system("python3 combine.py t_ibm.a t_ibm_rt.a > t_ibm_int.a")
    os.system("python3 combine.py t_hmm.a t_hmm_rt.a t_hmm_rs.a t_hmm_rt_rs.a > t_hmm_vote.a")
    os.system("python3 refine.py t_hmm_vote.a t_ibm_int.a")